import Aside from "@/components/website/store/Aside";
import Hero from "@/components/website/Hero";
import Store_Hrader from "@/components/website/store/Store_Hrader";
import LodeMore from "@/components/website/LodeMore";
export const metadata = {
  title: "Store Page",
  description: "Generated by create next app",
};

export default function StoreLayout({ children }) {
  return (
    <div className="w-full bg-[#F8F5F1] pt-4 sm:pt-6 pb-5">
      <div className="max-w-container  mx-auto  sm:px-6">
        <Hero
          subtitle="Store"
          title1="Explore Our"
          title2="Luxury"
          highlight="Collection"
          description="Discover premium furniture crafted for elegance."
          bgColor="#2C2016"
          image="/hero/hero.png"
        />
        <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr] gap-6 mt-6">
          <Aside />
          <div>
            <Store_Hrader />
            {children}
             <LodeMore />
          </div>
        </div>
      </div>
    </div>
  );
}