import Hero from '@/components/website/Hero'
import React from 'react'
import { IoIosStar } from "react-icons/io"
import { TbLeaf } from "react-icons/tb";
import { TbDiamond } from "react-icons/tb";
import { FaRegHeart } from "react-icons/fa";

export const metadata = {
    title: "About Page",
    description: "Generated by create next app",
};

export default function Page() {
    const stats = [
        { value: "12k+", label: "Homes transformed" },
        { value: "280+", label: "Curated products" },
        { value: "8", label: "Showrooms across India" },
        { value: "4.9", label: "Average rating", icon: <IoIosStar className="ml-1 text-[14px]" /> },
    ];
    const features = [
        {
            icon: <TbLeaf />,
            title: "Sustainable Craft",
            description: "Every piece is thoughtfully created using responsibly sourced materials. We believe furniture should be as kind to the planet as it is to your home.",
        },
        {
            icon: <TbDiamond />,
            title: "Premium Quality",
            description: "Every piece passes a 23-point quality check before it reaches your home. We back it with a 5-year warranty.",
        },
        {
            icon: <FaRegHeart />,
            title: "Customer Love",
            description: "We don't chase trends. We design furniture that ages gracefully and belongs in every chapter of your life.",
        },
    ];
    const teamMembers = [
        { initials: "AK", name: "Aarav Kumar", role: "Founder & CEO" },
        { initials: "SM", name: "Sanya Mehta", role: "Head of Design" },
        { initials: "VR", name: "Vikram Rao", role: "Chief Craftsman" },
        { initials: "PJ", name: "Preet Joshi", role: "Customer Experience" },
    ];

    return (
        <div className='w-full bg-[#F8F5F1] '>
            <div className="max-w-container mx-auto px-4 sm:px-6 my-4 sm:my-6">
               <Hero
 
  title1="Furniture crafted with"
  title2=""
  highlight="purpose"
  description="Founded in 2018, Nestro was born from a belief that beautiful furniture shouldn't be a luxury. We work directly with master craftsmen across India and Scandinavia to bring you pieces that are honest in material, thoughtful in design, and built to outlast trends."
  bgColor="#2C2016"
  image="/hero/hero.png"
  button1=""
  button2=""
/>
            </div>

            {/* Stats Section */}
            <div className="max-w-container mx-auto px-4 sm:px-6 my-6 sm:my-10">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-px bg-[#E8E0D5] rounded-xl overflow-hidden border border-[#E8E0D5]">
                    {stats.map((item, index) => (
                        <div key={index} className="bg-white p-4 sm:p-6 text-center">
                            <div className="text-[22px] sm:text-[28px] text-[#8B5E3C] font-medium mb-1 flex items-center justify-center flex-wrap">
                                {item.value} {item.icon && <span className="inline-flex">{item.icon}</span>}
                            </div>
                            <div className="text-[10px] sm:text-[11px] text-[#6B7280]">{item.label}</div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Values Section */}
            <div className="max-w-container mx-auto px-4 sm:px-6 my-8 sm:my-10">
                <div className="text-[10px] tracking-[0.2em] uppercase text-[#8B5E3C] mb-2.5">What drives us</div>
                <h2 className="text-[20px] sm:text-[24px] font-normal text-[#1E1E1E] leading-[1.2] tracking-[-0.02em]">Our Values</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5 mt-5">
                    {features.map((item, index) => (
                        <div key={index} className="bg-white border border-[#E8E0D5] rounded-xl p-5 sm:p-6">
                            <div className="text-[22px] sm:text-[26px] text-[#C6A27E] mb-3 flex items-center">
                                {item.icon}
                            </div>
                            <div className="text-[13px] sm:text-[14px] text-[#1E1E1E] mb-2 font-medium">
                                {item.title}
                            </div>
                            <div className="text-[11px] sm:text-[12px] text-[#6B7280] leading-[1.6]">
                                {item.description}
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Team Section */}
            <div className="max-w-container mx-auto px-4 sm:px-6 my-8 sm:my-10 pb-5">
                <div className="text-[10px] tracking-[0.2em] uppercase text-[#8B5E3C] mb-2.5">The people behind Nestro</div>
                <h2 className="text-[20px] sm:text-[24px] font-normal text-[#1E1E1E] leading-[1.2] tracking-[-0.02em]">Our Team</h2>
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-5 mt-5">
                    {teamMembers.map((member, index) => (
                        <div key={index} className="bg-white border border-[#E8E0D5] overflow-hidden rounded-xl">
                            <div className="h-24 sm:h-28 md:h-30 bg-[#F0EBE3] flex items-center justify-center text-[28px] sm:text-[32px] uppercase text-[#C6A27E] font-normal">
                                {member.initials}
                            </div>
                            <div className="p-3 sm:p-3.5">
                                <div className="text-[11px] sm:text-[12px] text-[#1E1E1E] font-medium">
                                    {member.name}
                                </div>
                                <div className="text-[9px] sm:text-[10px] text-[#6B7280] mt-0.5">
                                    {member.role}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    )
}